# Generated by Django 5.1.1 on 2024-10-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GCMCResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MoleculeName", models.CharField(max_length=100)),
                ("Uptake", models.FloatField(default=123.123)),
                ("FrameworkName", models.CharField(max_length=100)),
                ("ExternalPressure", models.FloatField()),
                ("Temperature", models.FloatField()),
                ("MoleculeDefinition", models.CharField(max_length=255)),
                ("Forcefield", models.CharField(max_length=100)),
                ("UnitCells", models.CharField(max_length=50)),
                ("NumberOfCycles", models.IntegerField()),
                ("NumberOfInitializationCycles", models.IntegerField()),
                ("TranslationProbability", models.FloatField()),
                ("ReinsertionProbability", models.FloatField()),
                ("SwapProbability", models.FloatField()),
                ("simulation_input_file", models.TextField()),
                ("simulation_output_directory", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
