# Generated by Django 5.1.1 on 2024-10-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_isothermfittingparameter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="isothermfittingparameter",
            name="error",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="isothermfittingparameter",
            name="optimizer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
